apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database: todo-app
  mongodb-url: mongodb://mongodb:27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  VITE_API_URL: "http://localhost:30500"  # Updated port to match backend