apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.js: |
    db.auth('admin', 'password')
    db = db.getSiblingDB('todo-app')
    db.createUser({
      user: 'admin',
      pwd: 'password',
      roles: [
        { role: 'readWrite', db: 'todo-app' }
      ]
    })