apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: YWRtaW4=  # admin in base64
  password: cGFzc3dvcmQ=  # password in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  username: YWRtaW4=  # admin in base64
  password: cGFzc3dvcmQ=  # password in base64