# templates/argocd-application.yaml
{{- if .Values.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.application.name }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: {{ .Values.argocd.application.project }}
  source:
    repoURL: {{ .Values.argocd.application.source.repoURL }}
    targetRevision: {{ .Values.argocd.application.source.targetRevision }}
    path: {{ .Values.argocd.application.source.path }}
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: {{ .Values.argocd.application.destination.namespace }}
  syncPolicy:
    {{- with .Values.argocd.application.syncPolicy }}
    automated:
      prune: {{ .automated.prune }}
      selfHeal: {{ .automated.selfHeal }}
    syncOptions:
      {{- range .syncOptions }}
      - {{ . }}
      {{- end }}
    {{- end }}
{{- end }}