{{- $ingress := .Values.ingress }}
{{- $namespace := .Values.namespace }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: {{ $namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Enable regex for paths
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-frontend
            port:
              number: 80
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: todo-backend
            port:
              number: 5000
