apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: todo-app
data:
  logstash.yml: |
    pipeline.workers: 2
    pipeline.batch.size: 125
    xpack.monitoring.enabled: false
    path.config: /usr/share/logstash/pipeline

  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/logstash.conf"
      
  logstash.conf: |
    input {
      beats {
        port => 5044
        host => "0.0.0.0"
      }
    }

    filter {
      if [kubernetes] {
        mutate {
          add_field => {
            "environment" => "kubernetes"
            "application" => "todo-app"
          }
        }
        json {
          source => "message"
          target => "parsed_json"
          skip_on_invalid_json => true
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://172.19.0.2:9200"]
        index => "todo-app-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.5.1
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: config-volume
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        env:
        - name: LS_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
      volumes:
      - name: config-volume
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: todo-app
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: ClusterIP