{{- $mongodb := .Values.mongodb }}
{{- $mongoExpress := .Values.mongoExpress }}
{{- $namespace := .Values.namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  username: {{ $mongodb.username | b64enc }}
  password: {{ $mongodb.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  username: {{ $mongoExpress.mongoDbUsername | b64enc }}
  password: {{ $mongoExpress.mongoDbPassword | b64enc }}
