namespace: todo-app

backend:
  image: ilyassepro/unique-backend:2.2
  port: 5000
  mongoDbUri: mongodb://admin:password@mongodb:27017/todo-app?authSource=admin

frontend:
  image: ilyassepro/unique-frontend:2.2
  port: 80
  apiUrl: http://myapp.local/api/todos

mongodb:
  image: mongo:latest
  username: admin
  password: password
  database: todo-app

mongoExpress:
  image: mongo-express:latest
  port: 8081
  mongoDbUsername: admin
  mongoDbPassword: password

ingress:
  enabled: true
  host: myapp.local

# values.yaml
argocd:
  enabled: true
  namespace: argocd
  application:
    name: todo-app
    project: default
    source:
      repoURL: https://github.com/ilyasse027/todo-app.git
      targetRevision: main
      path: todo-app-chart
    destination:
      server: https://kubernetes.default.svc
      namespace: todo-app
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
